; https://docs.platformio.org/page/projectconf.html

[platformio] 
default_envs = rUSB

[env] 
platform = espressif8266
board = esp07
framework = arduino
lib_extra_dirs = ~/Documents/Arduino/libraries
board_build.filesystem = littlefs
board_build.flash_mode = dout
board_build.ldscript = eagle.flash.1m128.ld
monitor_speed = 115200
upload_speed = 921600
upload_resetmethod = nodemcu
build_flags = -DVTABLES_IN_FLASH

[env:dOTA] 
build_flags = -DDEBUG_ESP_PORT=Serial
              -DDEBUG_ESP_WIFI
              -DDEBUG_ESP_CORE  
upload_port = 192.168.4.1
upload_protocol = espota

[env:dUSB] 
build_flags = -DDEBUG_ESP_PORT=Serial
              -DDEBUG_ESP_WIFI
              -DDEBUG_ESP_CORE  

[env:rOTA] 
upload_port = 192.168.4.1
upload_protocol = espota

[env:rUSB] 
;debug_tool = esp-prog
;upload_protocol = esp-prog
;build_flags = -D PIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK221
              ;-D PIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH_LOW_FLASH



;lib_deps =  ottowinter/ESPAsyncTCP-esphome @1.2.3
;            ottowinter/ESPAsyncWebServer-esphome @1.2.7
;            bblanchon/ArduinoJson @6.17.2
;            ottowinter/AsyncMqttClient-esphome @0.8.4
;            seeed-studio/Grove 4-Digit Display @1.0.0
;            milesburton/DallasTemperature @3.9.1


;eagle.flash.512k0.ld 512K (no SPIFFS)
;eagle.flash.512k64.ld 512K (64K SPIFFS)
;eagle.flash.512k128.ld 512K (128K SPIFFS)
;eagle.flash.1m0.ld 1M (no SPIFFS)
;eagle.flash.1m64.ld 1M (64K SPIFFS)
;eagle.flash.1m128.ld 1M (128K SPIFFS)
;eagle.flash.1m144.ld 1M (144K SPIFFS)
;eagle.flash.1m160.ld 1M (160K SPIFFS)
;eagle.flash.1m192.ld 1M (192K SPIFFS)
;eagle.flash.1m256.ld 1M (256K SPIFFS)
;eagle.flash.1m512.ld 1M (512K SPIFFS)
;eagle.flash.2m.ld 2M (1M SPIFFS)
;eagle.flash.4m1m.ld 4M (1M SPIFFS)
;eagle.flash.4m2m.ld 4M (2M SPIFFS)
;eagle.flash.4m.ld 4M (3M SPIFFS)
;eagle.flash.8m.ld 8M (7M SPIFFS)
;eagle.flash.16m.ld 16M (15M SPIFFS)

;-D PIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK3 NonOS SDK-pre-3.0 as of Jun 26, 2018
;-D PIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK221 NonOS SDK v2.2.1 (legacy) as of Jun 8, 2018
;-D PIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK22x_190313 NonOS SDK v2.2.x branch as of Mar 13, 2019
;-D PIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK22x_190703 NonOS SDK v2.2.x branch as of Jul 03, 2019 (default)
;-D PIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK22x_191024 NonOS SDK v2.2.x branch as of Oct 24, 2019
;-D PIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK22x_191105 NonOS SDK v2.2.x branch as of to Nov 05, 2019
;-D PIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK22x_191122 NonOS SDK v2.2.x branch as of to Nov 22, 2019